<template>
  <q-card :class="$q.platform.is.mobile ? '': 'q-ma-md'">
    <saved-file-dialog :error="true" :show="showPopup" :text-content="errorPopupMessage">
    </saved-file-dialog>
    <q-card-section>
      <div class="row justify-center">
        <div class="col-auto">
          <div class="q-pb-md text-primary"
               :class="$q.platform.is.mobile ? 'text-h4': 'text-h3'">
            <q-icon name="lock" :style="$q.platform.is.mobile ?
            'font-size: 3rem': 'font-size:4.5rem'">
            </q-icon>
            Decrypt
          </div>
        </div>
      </div>
      <div class="row q-pb-md">
        <div class="col-lg-12 col-xs-grow">
          <q-btn-toggle
            v-model="option"
            spread
            no-caps
            @input="optionChanged"
            color="white"
            text-color="black"
            :options="[
              {label: 'Read from file', value: 0, icon:'attach_file'},
              {label: 'Paste data', value: 1, icon:'create'}
            ]"/>
        </div>
      </div>
      <div class="row" v-if="option === 0">
        <div class="col-lg-12 col-xs-grow">
          <q-tooltip content-style="font-size: 14px">
            <p>
              If not generated by Text Encrypter, file must contain JSON with given structure: <br>
              { <br>
              algorithm: "aes-256-cbc", <br>
              encryptedDataHex: "*encrypted data in hexadecimal format*", <br>
              wasEncryptionKeySha256: "*boolean true if password is sha-256 checksum
              of the encryption key, false otherwise*", <br>
              ivVectorHex: "*IV vector in hexadecimal format*", <br>
              payloadPadding: "pkcs7", <br>
              }
            </p>
          </q-tooltip>
          <span class="text-subtitle2 text-primary text-bold">
            1. Data file .txt to decrypt (text/plain only, generated by Text Encrypter)
             </span>
          <file-reader @onFileUploaded="fileUploaded"></file-reader>
        </div>
      </div>
      <div class="row" v-if="option === 1">
        <div class="col-lg-12 col-xs-grow">
            <span class="text-subtitle2 text-primary text-bold">
           1. Text data to encrypt (generated by Text Encrypter)
          </span>
          <q-input
            v-model="encryptedDataText"
            filled
            class="limited-textarea-bigger"
            @input="parseEncryptedData"
            type="textarea"
          />
        </div>
      </div>
      <div class="row items-center q-pt-md" v-if="encryptedDataJson.algorithm">
        <div class="col-12">
          <span class="text-subtitle2 text-primary text-bold">
            2. Encryption Algorithm (readonly)
          </span>
          <q-input v-model="encryptedDataJson.algorithm" readonly/>
        </div>
      </div>
      <div class="row items-center q-pt-md"
           v-if="encryptedDataJson.wasEncryptionKeySha256 !== undefined">
        <div class="col-12">
          <span class="text-subtitle2 text-primary text-bold">
            3. Was password hashed using sha-256 (readonly)
          </span><br>
          <q-checkbox v-model="encryptedDataJson.wasEncryptionKeySha256"
                      label="Password hashed sha-256" :disable="true">
          </q-checkbox>
        </div>
      </div>
      <div class="row items-center q-pt-md" v-if="encryptedDataJson.ivVectorHex">
        <div class="col-12">
          <span class="text-subtitle2 text-primary text-bold">
            4. IV vector hex value (readonly)
          </span><br>
          <q-input v-model="encryptedDataJson.ivVectorHex" readonly/>

        </div>
      </div>
      <div class="row items-center q-pt-md" v-if="encryptedDataJson.encryptionDate">
        <div class="col-12">
          <span class="text-subtitle2 text-primary text-bold">
            4. Encryption date (readonly)
          </span><br>
          <q-input :value="encryptedDataJson.encryptionDate" readonly/>
        </div>
      </div>
      <div class="row q-pt-md" v-if="encryptedDataJson.encryptedDataHex">
        <div class="col-12">
          <span class="text-subtitle2 text-primary text-bold">
           4. Encryption key
          </span>
          <q-input bottom-slots v-model="encryptionKey"
                   :type="isPwd ? 'password' : 'text'"
                   label="Encryption key" counter>
            <template v-slot:prepend>
              <q-icon name="vpn_key"/>
            </template>
            <template v-slot:append>
              <q-icon
                :name="isPwd ? 'visibility_off' : 'visibility'"
                class="cursor-pointer"
                @click="isPwd = !isPwd"
              />
            </template>
          </q-input>
        </div>
      </div>
      <div class="row justify-center text-center items-center q-pt-md">
        <div class="col-grow">
          <q-btn color="primary" icon="lock" label="Decrypt" @click="decrypt"
                 :disable="(option === 0 && encryptionKey === null ||
                           encryptedDataJson.encryptedDataHex === null) ||
                           (option === 1 && encryptedDataJson === '')"
          />
        </div>
      </div>
    </q-card-section>
  </q-card>
</template>

<script>
import { decryptSymmetricCbc } from '../api/encryption-service';
import FileReader from './FileReader';
import SavedFileDialog from './SavedFileDialog';

export default {
  name: 'DecryptForm',
  components: { SavedFileDialog, FileReader },
  data() {
    return {
      option: 0,
      cbc: true,
      isPwd: true,
      useSha256: false,
      encryptionKey: null,
      encryptionKey2: null,
      decryptedFileContent: null,
      encryptedDataJson: {},
      showPopup: false,
      encryptedDataText: '',
      errorPopupMessage: 'Encryption data seems to be incorrect. Assure it is correct JSON structured content.',
    };
  },
  methods: {
    fileUploaded(fileContent) {
      try {
        this.encryptedDataJson = JSON.parse(fileContent);
      } catch (err) {
        console.log('Encrypted file data parsing error: ', err);
        this.showPopup = !this.showPopup;
      }
    },
    decrypt() {
      try {
        const asJsonFile = JSON.parse(JSON.stringify(this.encryptedDataJson));
        this.decryptedFileContent = decryptSymmetricCbc(
          asJsonFile.encryptedDataHex,
          this.encryptionKey,
          asJsonFile.ivVectorHex,
          asJsonFile.wasEncryptionKeySha256,
        );
        this.$emit('onDecryptionResult', this.decryptedFileContent);
      } catch (err) {
        console.log('Encrypted data parsing error: ', err);
        this.showPopup = !this.showPopup;
      }
    },
    parseEncryptedData() {
      try {
        this.encryptedDataJson = JSON.parse(this.encryptedDataText);
      } catch (err) {
        console.log('Pasted encrypted data is not Text Encrypter JSON object');
      }
    },
    optionChanged() {
      this.encryptedDataJson = {};
      this.encryptedDataText = '';
    },
  },
};
</script>
